### ISSUE TITLE
Confusion between versions

### ISSUE THREAD

**Issue by ricog** [kitchenplan/kitchenplan#114]
Is there a newer version in the works? The master branch is currently v2.1.18, but I also see a `version2` branch that was last touched in October 2014. Whether alive or dead, it may be useful to rename the branch.

The reason I ask is the `version2` branch shows signs of Linux support. Linux support would be useful to me.

**Comment by ricog** [comment]
@roderik Any comment on this?

**Comment by roderik** [comment]
version2 is actually the 2.0 branch, the current version is 2.1.x
For now, everything works like it should so no new versions are planned (barring the occasional bugfix and support for the next osx version starting after wwdc)

As far as linux and windows support, we did remove them in 2.1 since nobody was using them, let alone maintaining it. A few months after 2.1, we got a pul request adding a lot of windows support for the version2 branch. I merged this in but since i don't have any windows computers, there is no way i can maintain this.

Removing of the support is actually rather limited. The setup and provision steps assume osx and could be easily be extended to handle linux installs as well. I'll gladly merge pull requests for this btw. The config file parsing still supports other operating systems so that should work without changes.

**Comment by ricog** [comment]
Thank you for the clarification. Makes sense now.

I'm reviewing a few other tools for my linux needs, but may come back to kitchenplan with PRs. There's a lot to like about it. I'm only maintaining personal machines, not an entire enterprise, so don't get the benefits of scale.
